### ISSUE TITLE
has('mac') not working?

### ISSUE THREAD

**Issue by muhh** [freistil/dotfiles#7]
https://github.com/freistil/dotfiles/blob/master/vimrc#L273 doesn't seem to work?
I found http://stackoverflow.com/questions/10139972/vim-hasmacunix-or-hasmac-do-not-work which suggests this is dependent on macvim?

Or am I using it wrong?

**Comment by geewiz** [comment]
Could very well be that it depends on MacVim... I probably had installed MacVim before I copied and started using this configuration. Does it make sense to simply make sure MacVim is installed?

**Comment by muhh** [comment]
Sadly no. It should work in vim as well, no?

**Comment by geewiz** [comment]
I guess you'll have to be a bit more specific about your issue. To be clear: On my laptop, the configuration  works both with the graphical UI and in the terminal.
